### ISSUE TITLE
forecast.gts silently produces NAN for all levels when at least one base level is all zeros

### ISSUE THREAD

**Issue by dashaub** [robjhyndman/hts#11]
hts version is 4.4 from CRAN
See the reproducible example below

    library(hts)
    myhts <- hts(cbind(wineind, 0))

    # The total is fine here
    aggts(myhts)

    # The forecast produces NAN at all levels, 
    # including Total and wineind
    forecast.gts(myhts)

**Comment by robjhyndman** [comment]
This issue does not occur with v4.5 on github.
