### ISSUE TITLE
hts() does not preserve frequency of bottom level time series

### ISSUE THREAD

**Issue by jwpestrak** [robjhyndman/hts#12]
# sessionInfo()
    # hts_4.5
    # forecast_6.1
    nodes <- list(2, c(3, 2))
    abc <- ts(5 + matrix(sort(rnorm(500)), ncol = 5, nrow = 100), frequency = 7)
    frequency(abc) # 7
    frequency(hts(abc, nodes)) # 1

My intention is that after I create a `hts` object, I'd like to obtain the first `K` fourier terms of each underlying time series. 

When I call `fourier(hts(abc, nodes), K = 5)`, I am thrown an exception - "K must not be greater than period/2" because `frequency(hts(abc, nodes))` is 1.

**Comment by earowang** [comment]
`hts()` returns an hts object that includes not only bottom time series but also its node structure. Hence `frequency()` will not work properly for `hts()`. I suppose what you want is to get all the time series from `hts()`, so try the following:

```r
nodes <- list(2, c(3, 2))
abc <- ts(5 + matrix(sort(rnorm(500)), ncol = 5, nrow = 100), frequency = 7)
frequency(abc) # 7
hts.abc <- hts(abc, nodes) # it's an hts object
all.abc <- aggts(hts.abc) # gives all the time series
frequency(all.abc) # 7
fourier(all.abc, K = 3)
```
