### ISSUE TITLE
Forecast.gts() does not tell us which bottom level series throws the error

### ISSUE THREAD

**Issue by Ic3fr0g** [robjhyndman/hts#23]
Here is the code I am running - 
` fit <- forecast.gts(new_ts,h = 365,fmethod = "arima",xreg = train,newxreg = holidayf$Total,method =       "comb")`

`Error in auto.arima(x, lambda = lambda, xreg = xreg, parallel = FALSE,  : 
  No suitable ARIMA model found
In addition: Warning message:
In auto.arima(x, lambda = lambda, xreg = xreg, parallel = FALSE,  :
  Unable to calculate AIC offset`
It would massively help if I knew which bottom level series is causing the error so that I can isolate it.

**Comment by robjhyndman** [comment]
Use the built-in debugging tools. See https://stat.ethz.ch/R-manual/R-devel/library/utils/html/recover.html

**Comment by robjhyndman** [comment]
Also, please update to the latest version of the package. I have made auto.arima more robust recently.
